# File: docker-compose.yml

services:
  fastbot-ros2-real:
    #build:
    #  context: .
    #  dockerfile: Dockerfile.fastbot-ros2-real
    #image: stud/stud-cp22:fastbot-ros2-real
    image: robertkwan/fastbot-ros2-docker-real:fastbot-ros2-real
    container_name: fastbot-ros2-real
    network_mode: host
    restart: always
    devices:
      - /dev/video0:/dev/video0
      - /dev/ttyACM0:/dev/lslidar
      - /dev/ttyUSB0:/dev/arduino_nano
    environment:
      - DISPLAY=${DISPLAY}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=1
      - ROS_IPV6=off
    group_add:
      - dialout
    privileged: true

  fastbot-ros2-real-slam:
    #build:
    #  context: .
    #  dockerfile: Dockerfile.fastbot-ros2-real-slam
    #image: stud/stud-cp22:fastbot-ros2-real-slam
    image: robertkwan/fastbot-ros2-docker-real:fastbot-ros2-real-slam
    container_name: fastbot-ros2-real-slam
    depends_on:
      - fastbot-ros2-real
    network_mode: host
    restart: always
    environment:
      - DISPLAY=${DISPLAY}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=1
      - ROS_IPV6=off
    privileged: true
    command: bash -c "source /opt/ros/humble/setup.bash && source install/setup.bash && ros2 launch fastbot_slam cartographer.launch.py && ros2 daemon stop"
    #command: bash -c "cd /ros2_ws && colcon build && source install/setup.bash && ros2 launch fastbot_slam cartographer.launch.py"

